name: Deploy Application Docker Image to EC2 instance

on:
  push:
    branches: [main]
    paths:
    - 'app.py'
    - 'Dockerfile'
    - 'requirements-lock.txt'
    - 'setup.py'
    - 'templates/**'
    - 'static/**'
    - 'config/**'
    - 'visa_approval_prediction/**'
    - '.github/workflows/**'

env:
  ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
  ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
  IMAGE_TAG: latest

jobs:
  Continuous-Integration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Login to Amazon ECR Public
        run: |
          aws ecr-public get-login-password --region us-east-1 | \
          docker login --username AWS --password-stdin public.ecr.aws

      - name: Build Docker Image
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .

      - name: Push Docker Image
        run: |
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

  Continuous-Deployment:
    needs: Continuous-Integration
    runs-on: self-hosted

    steps:
      
      - name: Pull Latest Image
        run: |
          docker pull $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Stop Existing Container
        run: |
          docker stop visa-prediction-app || true
          docker rm visa-prediction-app || true

      - name: Run Docker Container
        run: |
          docker run -d \
            --restart unless-stopped \
            --name visa-prediction-app \
            -e AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}" \
            -e AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
            -e MONGODB_URL="${{ secrets.MONGODB_URL }}" \
            -p 8080:8080 \
            $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG